### ISSUE TITLE
detect flex box

### ISSUE THREAD

**Issue by brentonstrine** [phiggins42/has.js#107]
Ability to detect flex box is more important now as it's being used more often and fallbacks need to be created.

**Comment by brentonstrine** [comment]
would this strategy work? https://gist.github.com/davidhund/b995353fdf9ce387b8a2

**Comment by brentonstrine** [comment]
Created PR for this, see https://github.com/phiggins42/has.js/pull/108

**Comment by phiggins42** [comment]
thanks!
